# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    # Repository interfaces binding
    App\Domain\Repository\ServiceRepositoryInterface:
        alias: App\Infrastructure\Repository\ServiceRepository

    App\Domain\Repository\UtilisateurRepositoryInterface:
        alias: App\Infrastructure\Repository\UtilisateurRepository

    App\Domain\Repository\PersonneExterneRepositoryInterface:
        alias: App\Infrastructure\Repository\PersonneExterneRepository

    App\Domain\Repository\CourrierRepositoryInterface:
        alias: App\Infrastructure\Repository\CourrierRepository

    App\Domain\Repository\HistoriqueActionRepositoryInterface:
        alias: App\Infrastructure\Repository\HistoriqueActionRepository

    App\Domain\Repository\PieceJointeRepositoryInterface:
        alias: App\Infrastructure\Repository\PieceJointeRepository

    App\Domain\Repository\AccuseReceptionRepositoryInterface:
        alias: App\Infrastructure\Repository\AccuseReceptionRepository

    App\Domain\Repository\NotificationRepositoryInterface:
        alias: App\Infrastructure\Repository\NotificationRepository

    App\Domain\Repository\SessionTraceRepositoryInterface:
        alias: App\Infrastructure\Repository\SessionTraceRepository

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
